# Use the official Python image as the base image
FROM python:3.8

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt /app/

# Install dependencies
RUN pip install -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app/

# # Expose port 8000 to allow communication to/from server
# EXPOSE 8000
#
# # Command to run the Django server
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
